<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    //

    public function comments()
    {
        return $this->hasMany(BlogComment::class , 'blog_id');
    }

    public function delete()
    {
        @unlink(storage_path('app/blog/thumbnail/'.$this->image));
        @unlink(storage_path('app/blog/'.$this->image));

        $this->comments()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
