<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    public function products()
    {
        return $this->hasMany(Product::class , 'category_id');
    }

    public function delete()
    {
        foreach ($this->products() as $product){
            @unlink(storage_path('app/products/'.$product->image));
            $product->comments()->delete();
            $product->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
