<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
    public function details()
    {
        return $this->hasOne(OrderDetail::class , 'order_id');
    }

    public function delete()
    {
        $this->details()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
