<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Session;

class Product extends Model
{
    //
    public function category()
    {
        return $this->belongsTo(Category::class , 'category_id');
    }

    public function price()
    {
        $price = Session::get('currency');
        switch ($price){
            case ('usd') :
                return $this->usd_price.' Usd';
                break;

            case ('eur') :
                return $this->eur_price.' Euro';
                break;

            case ('aed') :
                return $this->uae_price.' Aed';
                break;

            default :
                return $this->egp_price.' Egp';
        }
    }

    public function comments()
    {
        return $this->hasMany(ProductComment::class , 'product_id');
    }

    public function delete()
    {
        @unlink(storage_path('app/products/'.$this->image));

        $this->comments()->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
